In [189]:
import pandas as pd

data = pd.read_csv('../data/processed/placement_with_desirability.csv')
data.columns

/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['Unnamed: 0', 'CASE_REF_ID', 'CLIENT_ID', 'CL_KEY', 'PLCMNT_KEY',
       'ABS_KEY', 'ALT_LOC_KEY', 'MCI_ID', 'BIRTH_YEAR', 'GENDER',
       'RACE_GROUP', 'REG_OFFICE_RMVLDT', 'HOME_RMVL_KEY', 'CLIENT_RMVLDT',
       'HOME_RMVL_SEQ_NBR', 'RMVL_TYPE', 'RMVL_DATE', 'RTRN_DATE', 'RMVL_YEAR',
       'RMVL_AGE', 'RMVL_OPEN_PLMT', 'RMVL_OPEN', 'RMVL_LOS',
       'RMVD_FRM_CL_KEY', 'PLCMNT_TYPE', 'RMVL_TYPE.1',
       'Placement.Referral.Type', 'TYPE_PLACEMENT', 'PLCMNT_SEQ_NBR',
       'ANALYSIS_ENTRY_DT', 'ANALYSIS_EXIT_DT', 'PLMT_YEAR', 'PLMT_AGE',
       'PLMT_OPEN', 'PLMT_LOS', 'RMVL_LATEST_PLMT', 'RMVL_PLMT_NO',
       'CLIENT_PLMT_NO', 'CLIENT_CYF_PLMT_NO', 'CW.Exit.Reason.Type',
       'CW.Exit.Reason', 'Placement.Exit.Reason', 'End.Care.Reason',
       'SRVC_GROUP_2', 'ANALYSIS_CARETYPE', 'FACILITY_ID', 'AGENCY_ID',
       'exit_reason', 'desirability', 'notes'],
      dtype='object')

In [78]:
cw = pd.read_csv('../data/processed/exit_cw_status.csv')
cw.columns = ['exit_reason', 'desirability', 'notes']
data = pd.merge(data, cw, left_on='CW.Exit.Reason', right_on='exit_reason')
data.to_csv('../data/processed/placement_with_desirability.csv')

In [72]:
# data = pd.read_csv('/Users/cipherpol/Downloads/rp_placements_clean.csv')
col_list = ['CL_ID', 'MCI_ID.x','CASE_REF_ID', 'SPELLONE', 'HOME_RMVL_KEY', 'RMVL_TYPE', 'RMVL_DATE', 'RTRN_DATE', 'RMVL_LOS', 'PLMT_YEAR', 'SEQ_NBR', 'ANALYSIS_ENTRY_DT', 'ANALYSIS_EXIT_DT', 'CW.Exit.Reason', 'Placement.Exit.Reason' 'End.Care.Reason' ]
placement_col_list = ['CASE_REF_ID', 'CLIENT_ID', 'HOME_RMVL_KEY', 'RMVL_TYPE', 'RMVL_DATE', 'RTRN_DATE', 'RMVL_LOS', 'RMVD_FROM_CL_KEY', 'ANALYSIS_ENTRY_DT', 'ANALYSIS_EXIT_DT', 'CW.Exit.Reason', 'Placement.Exit.Reason' 'End.Care.Reason', 'ANALYSIS_CARETYPE' ]

data.ix[:, placement_col_list ].head(20)

,CASE_REF_ID,CLIENT_ID,HOME_RMVL_KEY,RMVL_TYPE,RMVL_DATE,RTRN_DATE,RMVL_LOS,RMVD_FROM_CL_KEY,ANALYSIS_ENTRY_DT,ANALYSIS_EXIT_DT,CW.Exit.Reason,Placement.Exit.ReasonEnd.Care.Reason,ANALYSIS_CARETYPE
0,40895,800035,5293,First Entry,2010-12-05,2010-12-06,2,NaN,2010-12-05,2010-12-06,Return Home (Ends the Home Removal),NaN,Congregate Care
1,40895,800035,5294,Reentry,2011-02-10,2011-08-15,187,NaN,2011-02-10,2011-03-16,Placement/Custody by Juvenile Probation,NaN,Congregate Care
2,40895,800035,5294,Reentry,2011-02-10,2011-08-15,187,NaN,2011-03-16,2011-05-20,Court Ordered (For JPO use only),NaN,Congregate Care
3,40895,800035,5294,Reentry,2011-02-10,2011-08-15,187,NaN,2011-05-20,2011-08-15,Return Home (Ends the Home Removal),NaN,Congregate Care
4,40895,800035,16284,Reentry,2013-02-14,2013-02-14,1,NaN,2013-02-14,2013-02-14,Return Home (Ends the Home Removal),NaN,Congregate Care
5,43691,800038,10391,First Entry,2011-08-17,2012-08-03,353,NaN,2011-08-17,2011-11-04,**Placed in Group / Residential**,NaN,Congregate Care
6,43691,800038,10391,First Entry,2011-08-17,2012-08-03,353,NaN,2011-11-04,2012-01-03,Abscondance/Runaway,NaN,Congregate Care
7,43691,800038,10391,First Entry,2011-08-17,2012-08-03,353,NaN,2012-01-30,2012-08-03,Return Home (Ends the Home Removal),NaN,Congregate Care
8,43724,800043,7215,First Entry,2010-05-21,2011-01-13,238,NaN,2010-05-28,2010-07-07,**Placement Temporarily Unable to Care for Chi...,NaN,Kinship Care
9,43724,800043,7215,First Entry,2010-05-21,2011-01-13,238,NaN,2010-07-09,2010-07-19,Abscondance/Runaway,NaN,Foster Care
10,43724,800043,2771,Reentry,2011-03-10,2012-05-11,429,NaN,2011-03-10,2011-05-09,**Youth Requires Different Level of Care**,NaN,Congregate Care
11,43724,800043,2771,Reentry,2011-03-10,2012-05-11,429,NaN,2011-05-27,2011-08-01,**Placed in Group / Residential**,NaN,Congregate Care
12,43724,800043,2771,Reentry,2011-03-10,2012-05-11,429,NaN,2011-08-01,2012-02-16,Placement/Custody by Juvenile Probation,NaN,Congregate Care
13,43724,800043,2771,Reentry,2011-03-10,2012-05-11,429,NaN,2012-03-02,2012-04-04,Placement Cannot Meet the Child's Behavioral T...,NaN,Congregate Care
14,43724,800043,2771,Reentry,2011-03-10,2012-05-11,429,NaN,2012-04-04,2012-05-11,Return Home (Ends the Home Removal),NaN,Congregate Care
15,43724,800043,15658,Reentry,2012-12-21,2012-12-31,11,NaN,2012-12-21,2012-12-31,Return Home (Ends the Home Removal),NaN,Congregate Care
16,43724,800043,23289,Reentry,2014-10-03,2014-10-14,12,NaN,2014-10-03,2014-10-14,Return Home (Ends the Home Removal),NaN,Congregate Care
17,43724,800043,25525,Reentry,2015-06-18,2015-06-26,9,NaN,2015-06-18,2015-06-26,Return Home (Ends the Home Removal),NaN,Congregate Care
18,43724,800043,27567,Reentry,2015-12-18,2015-12-22,5,NaN,2015-12-18,2015-12-22,Return Home (Ends the Home Removal),NaN,Congregate Care
19,43724,800044,7213,First Entry,2010-05-14,2010-05-28,15,NaN,2010-05-14,2010-05-28,Permanent Placement in the Home of a 'Fit and ...,NaN,Foster Care

In [221]:
import pandas as pd
import pdb

class Component:
    
    def __init__(self, name, calculate):
        self.name = name
        accepted_calculations = ['total', 'average', 'dummy']
        if calculate in accepted_calculations:
            self.calculate = calculate
        else:
            raise Exception('calculate method must be', str(accepted_calculations))
        
    def __str__(self):
        return self.name

class DataSet:
    
    def __init__(self, data, components):
        self.data = data
        self.components = []
        if len(components) > 0:
            for component in components:
                self.components.append(component)
        
    def add_component(self, component):
        self.components.append(component)
        
    @property
    def house_str(self):
        return 'HOME_RMVL_KEY'
    
    @property
    def house_id_column(self):
        return self.data[self.house_str]
    
    @property
    def base_df(self):
        home_id = self.data[self.house_str].value_counts().index
        home_df = pd.DataFrame(index=home_id, data=home_id)
        home_df.columns = ['home_id']
        return home_df
        
    @staticmethod
    def restructure_column_names(df, component):
        new_names = [component.name + '_' + str(column) for column in df.columns.values]
        df.columns = new_names
        return df
    
    def get_totals(self, component):
        grouped = self.data.groupby(self.house_str).count()[component.name]
        grouped = pd.DataFrame(index=grouped.index, data=grouped)
        grouped.columns = [component.name + '_count']
        return grouped
    
    
    def get_dummy(self, component):
        crosstab = pd.crosstab(self.house_id_column, self.data[component.name])
        new_names = [component.name + '_' + str(column) for column in crosstab.columns.values]
        crosstab.columns = new_names
        return crosstab
    
    def get_average(self, component):
        grouped = self.data.groupby(self.house_str).mean()[component.name]
        grouped = pd.DataFrame(index=grouped.index, data=grouped)
        grouped.columns = [component.name + '_avg']
        return grouped
    
    def run_calculation(self, component):
        if component.calculate == 'average':
            calc = self.get_average(component)
        elif component.calculate == 'total':
            calc = self.get_totals(component)
        elif component.calculate == 'dummy':
            calc = self.get_dummy(component)
        else:
            raise Exception('calculations for {comp} component not supported'.format(comp=component.name))
        return calc
    
    @staticmethod
    def outcome_function(row, desirability):
        desirability = desirability[0].upper() + desirability[1:]
        if row == desirability:
            return 1
        else:
            return 0
            
    def create_outcome_var(self):
        self.data['outcome'] = self.data.apply(lambda x: outcome_function(x, 'good'), axis=1)
        
    def finalize_df(self):
        data = self.base_df
        for component in self.components:
            print('working on', component.name)
            calc = self.run_calculation(component)
            # pdb.set_trace()
            data = pd.merge(data, calc, left_on='home_id', right_index=True, how='left')
        return data

In [222]:
comp_dict = {}
comp_dict['RMVL_LOS'] = 'average'
comp_dict['CASE_REF_ID'] = 'total'
comp_dict['CLIENT_ID'] = 'total'
comp_dict['GENDER'] = 'dummy'
comp_dict['RACE_GROUP'] = 'dummy'
comp_dict['RMVL_TYPE'] = 'dummy'
comp_dict['RMVL_AGE'] = 'total'
comp_dict['PLCMNT_TYPE'] = 'dummy'
comp_dict['TYPE_PLACEMENT'] = 'dummy'
comp_dict['ANALYSIS_CARETYPE'] = 'dummy'
components = []
for key, value in comp_dict.items():
    comp = Component(key, value)
    components.append(comp)
self = DataSet(data, components)
[component.name for component in self.components]

['RMVL_AGE',
 'RMVL_TYPE',
 'RACE_GROUP',
 'GENDER',
 'ANALYSIS_CARETYPE',
 'TYPE_PLACEMENT',
 'RMVL_LOS',
 'CLIENT_ID',
 'PLCMNT_TYPE',
 'CASE_REF_ID']

In [223]:
self.finalize_df()

working on RMVL_AGE
working on RMVL_TYPE
working on RACE_GROUP
working on GENDER
working on ANALYSIS_CARETYPE
working on TYPE_PLACEMENT
working on RMVL_LOS
working on CLIENT_ID
working on PLCMNT_TYPE
working on CASE_REF_ID

,home_id,RMVL_AGE_count,RMVL_TYPE_First Entry,RMVL_TYPE_Reentry,RACE_GROUP_African American,RACE_GROUP_Other Single Race Identified,RACE_GROUP_Two or More Races Identified,RACE_GROUP_Unknown,RACE_GROUP_White,GENDER_Female,GENDER_Male,GENDER_Unknown,ANALYSIS_CARETYPE_Congregate Care,ANALYSIS_CARETYPE_Foster Care,ANALYSIS_CARETYPE_Independent Living,ANALYSIS_CARETYPE_Kinship Care,ANALYSIS_CARETYPE_Other/Alternative,ANALYSIS_CARETYPE_RTF,ANALYSIS_CARETYPE_Unknown,TYPE_PLACEMENT_Non-Paid,TYPE_PLACEMENT_Paid,RMVL_LOS_avg,CLIENT_ID_count,PLCMNT_TYPE_CYF,PLCMNT_TYPE_JPO,CASE_REF_ID_count
884,884,26,26,0,26,0,0,0,0,0,26,0,11,9,0,4,1,1,0,2,24,2417,26,25,1,26
9030,9030,25,0,25,25,0,0,0,0,25,0,0,21,3,0,1,0,0,0,6,19,1607,25,17,8,25
2148,2148,24,24,0,24,0,0,0,0,0,24,0,20,0,0,2,1,1,0,10,14,2565,24,13,11,24
6396,6396,23,23,0,23,0,0,0,0,0,23,0,22,0,0,0,0,1,0,3,20,1847,23,0,23,23
4551,4551,22,0,22,0,0,0,0,22,0,22,0,21,0,0,1,0,0,0,4,18,2174,22,6,16,22
8613,8613,20,0,20,20,0,0,0,0,0,20,0,14,2,0,4,0,0,0,3,17,1623,20,13,7,20
16398,16398,20,0,20,20,0,0,0,0,0,20,0,17,0,1,1,1,0,0,9,11,1240,20,7,13,20
8197,8197,20,0,20,0,0,20,0,0,0,20,0,14,0,2,4,0,0,0,8,12,1472,20,9,11,20
5860,5860,20,20,0,20,0,0,0,0,0,20,0,15,0,0,4,0,1,0,4,16,2781,20,11,9,20
6093,6093,19,0,19,0,0,0,0,19,0,19,0,13,1,2,2,0,1,0,3,16,2155,19,9,10,19
723,723,19,19,0,0,0,0,19,0,19,0,0,8,3,1,3,3,1,0,5,14,2341,19,18,1,19
4435,4435,19,19,0,0,0,0,0,19,0,19,0,18,0,0,1,0,0,0,4,15,2678,19,7,12,19
11212,11212,18,0,18,18,0,0,0,0,18,0,0,11,0,0,7,0,0,0,0,18,1772,18,18,0,18
6056,6056,18,18,0,18,0,0,0,0,0,18,0,13,2,2,1,0,0,0,0,18,2615,18,18,0,18
11934,11934,18,0,18,18,0,0,0,0,0,18,0,15,0,1,0,1,1,0,5,13,954,18,10,8,18
14045,14045,18,0,18,0,0,0,0,18,18,0,0,4,2,0,7,3,2,0,5,13,1519,18,18,0,18
9548,9548,18,0,18,18,0,0,0,0,0,18,0,7,5,0,6,0,0,0,2,16,1814,18,16,2,18
4328,4328,18,18,0,18,0,0,0,0,18,0,0,12,0,3,3,0,0,0,6,12,3711,18,7,11,18
3534,3534,17,0,17,17,0,0,0,0,0,17,0,10,1,1,3,1,1,0,2,15,4167,17,17,0,17
19594,19594,17,0,17,0,0,0,0,17,17,0,0,15,0,0,1,1,0,0,5,12,995,17,9,8,17
5348,5348,17,17,0,0,0,0,0,17,17,0,0,10,2,1,0,2,2,0,4,13,4692,17,17,0,17
2817,2817,17,17,0,17,0,0,0,0,0,17,0,15,0,1,1,0,0,0,5,12,4356,17,5,12,17
2915,2915,17,17,0,17,0,0,0,0,17,0,0,11,4,1,0,0,1,0,2,15,2176,17,13,4,17
11612,11612,17,0,17,17,0,0,0,0,17,0,0,10,1,0,6,0,0,0,8,9,1297,17,11,6,17
9852,9852,17,17,0,17,0,0,0,0,17,0,0,15,0,0,2,0,0,0,6,11,1885,17,8,9,17
17639,17639,16,0,16,16,0,0,0,0,0,16,0,15,0,1,0,0,0,0,2,14,1183,16,7,9,16
16441,16441,16,16,0,16,0,0,0,0,16,0,0,11,0,0,5,0,0,0,0,16,1267,16,16,0,16
10899,10899,16,16,0,16,0,0,0,0,16,0,0,10,2,0,4,0,0,0,0,16,1788,16,16,0,16
8090,8090,16,16,0,0,0,0,0,16,0,16,0,12,0,0,1,3,0,0,5,11,1696,16,10,6,16
12265,12265,16,0,16,0,0,0,16,0,16,0,0,9,1,1,1,3,1,0,4,12,1311,16,16,0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14900,14900,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,2,1,0,1,1
10806,10806,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,232,1,0,1,1
8759,8759,1,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,1,0,2,1,0,1,1
23096,23096,1,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,214,1,1,0,1
16955,16955,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,4,1,0,1,1
29245,29245,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,2,1,0,1,1
27198,27198,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,2,1,0,1,1
25151,25151,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2,1,0,1,1
531,531,1,1,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,35,1,1,0,1
2578,2578,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,340,1,1,0,1
4625,4625,1,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,47,1,1,0,1
6672,6672,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,110,1,1,0,1
12757,12757,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,4,1,0,1,1
8663,8663,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,5,1,0,1,1
20953,20953,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2,1,0,1,1
18906,18906,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,1,0,1,1
29149,29149,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,4,1,0,1,1
27102,27102,1,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,2,1,0,1,1
25055,25055,1,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,1,0,1,1
4593,4593,1,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1778,1,1,0,1
2546,2546,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,1028,1,1,0,1
499,499,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,4,1,0,1,1
14836,14836,1,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,1411,1,0,1,1
23032,23032,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,3,1,0,1,1
20985,20985,1,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,4,1,0,1,1
18938,18938,1,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,4,1,0,1,1
16891,16891,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,4,1,1,0,1
27134,27134,1,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,289,1,1,0,1
25087,25087,1,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,1,0,2,1,0,1,1
2049,2049,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,2223,1,1,0,1

In [211]:
self.data.head(20)

,Unnamed: 0,CASE_REF_ID,CLIENT_ID,CL_KEY,PLCMNT_KEY,ABS_KEY,ALT_LOC_KEY,MCI_ID,BIRTH_YEAR,GENDER,RACE_GROUP,REG_OFFICE_RMVLDT,HOME_RMVL_KEY,CLIENT_RMVLDT,HOME_RMVL_SEQ_NBR,RMVL_TYPE,RMVL_DATE,RTRN_DATE,RMVL_YEAR,RMVL_AGE,RMVL_OPEN_PLMT,RMVL_OPEN,RMVL_LOS,RMVD_FRM_CL_KEY,PLCMNT_TYPE,RMVL_TYPE.1,Placement.Referral.Type,TYPE_PLACEMENT,PLCMNT_SEQ_NBR,ANALYSIS_ENTRY_DT,ANALYSIS_EXIT_DT,PLMT_YEAR,PLMT_AGE,PLMT_OPEN,PLMT_LOS,RMVL_LATEST_PLMT,RMVL_PLMT_NO,CLIENT_PLMT_NO,CLIENT_CYF_PLMT_NO,CW.Exit.Reason.Type,CW.Exit.Reason,Placement.Exit.Reason,End.Care.Reason,SRVC_GROUP_2,ANALYSIS_CARETYPE,FACILITY_ID,AGENCY_ID,exit_reason,desirability,notes
0,0,40895,800035,71940,11084,-1,-1,1000507684,1994,Male,African American,NaN,5293,80003540517,1,First Entry,2010-12-05,2010-12-06,2010,16,N,N,2,61083,JPO,JPO,JPO,Paid,13199,2010-12-05,2010-12-06,2010,16,N,2,Y,1,1,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,466,NaN,Return Home (Ends the Home Removal),Good,NaN
1,1,40895,800035,71940,25045,-1,-1,1000507684,1994,Male,African American,JPO,5294,80003540584,2,Reentry,2011-02-10,2011-08-15,2011,16,N,N,187,61083,JPO,JPO,JPO,Paid,25145,2011-05-20,2011-08-15,2011,17,N,88,Y,3,4,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,13038,354,Return Home (Ends the Home Removal),Good,NaN
2,2,40895,800035,71940,33235,-1,-1,1000507684,1994,Male,African American,JPO,16284,80003541319,3,Reentry,2013-02-14,2013-02-14,2013,18,N,N,1,61083,JPO,JPO,Non-Paid,Non-Paid,32645,2013-02-14,2013-02-14,2013,18,N,1,Y,1,5,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
3,3,43691,800038,69387,23303,-1,-1,1000552576,1994,Male,African American,SRO,10391,80003840772,1,First Entry,2011-08-17,2012-08-03,2011,16,N,N,353,69386,CYF,CYF,Online Service Request,Paid,23404,2012-01-30,2012-08-03,2012,17,N,187,Y,3,3,3,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,2735,37,Return Home (Ends the Home Removal),Good,NaN
4,4,43724,800043,57577,25021,-1,-1,1000128407,1996,Female,African American,CRO,2771,80004340612,2,Reentry,2011-03-10,2012-05-11,2011,15,N,N,429,31227,CYF,CYF,Shelter,Paid,25106,2012-04-04,2012-05-11,2012,16,N,38,Y,5,7,7,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,2898,640,Return Home (Ends the Home Removal),Good,NaN
5,5,43724,800043,57577,31975,-1,-1,1000128407,1996,Female,African American,NaN,15658,80004341264,3,Reentry,2012-12-21,2012-12-31,2012,16,N,N,11,31227,JPO,JPO,Non-Paid,Non-Paid,31364,2012-12-21,2012-12-31,2012,16,N,11,Y,1,8,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
6,6,43724,800043,57577,47794,-1,-1,1000128407,1996,Female,African American,EXECUTIVE,23289,80004341915,4,Reentry,2014-10-03,2014-10-14,2014,18,N,N,12,NaN,JPO,JPO,Non-Paid,Non-Paid,47085,2014-10-03,2014-10-14,2014,18,N,12,Y,1,9,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
7,7,43724,800043,57577,52136,-1,-1,1000128407,1996,Female,African American,EXECUTIVE,25525,80004342173,5,Reentry,2015-06-18,2015-06-26,2015,19,N,N,9,NaN,JPO,JPO,Non-Paid,Non-Paid,51180,2015-06-18,2015-06-26,2015,19,N,9,Y,1,10,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
8,8,43724,800043,57577,56375,-1,-1,1000128407,1996,Female,African American,CRO,27567,80004342356,6,Reentry,2015-12-18,2015-12-22,2015,19,N,N,5,NaN,JPO,JPO,Non-Paid,Non-Paid,54956,2015-12-18,2015-12-22,2015,19,N,5,Y,1,11,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
9,9,43724,800044,69388,10928,-1,-1,1000552578,1997,Female,African American,CRO,7214,80004440327,2,Reentry,2010-05-29,2010-12-22,2010,13,N,N,208,106773,CYF,CYF,Non-Posted,Paid,7300,2010-05-29,2010-12-22,2010,13,N,208,Y,1,2,2,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Foster Care,Kinship Care,12578,84,Return Home (Ends the Home Removal),Good,NaN
10,10,43724,800045,32029,5033,-1,-1,1000376721,2000,Female,African American,CRO,7216,80004540319,1,First Entry,2010-05-21,2010-12-22,2010,9,N,N,216,106773,CYF,CYF,Non-Posted,Paid,7368,2010-05-29,2010-12-22,2010,9,N,208,Y,2,2,2,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Foster Care,Kinship Care,12578,84,Return Home (Ends the Home Removal),Good,NaN
11,11,43724,800046,69389,10930,-1,-1,1000552579,2001,Female,African American,CRO,7212,80004640319,1,First Entry,2010-05-21,2010-12-22,2010,8,N,N,216,106773,CYF,CYF,Non-Posted,Paid,7306,2010-05-29,2010-12-22,2010,8,N,208,Y,2,2,2,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Foster Care,Kinship Care,12578,84,Return Home (Ends the Home Removal),Good,NaN
12,12,43724,800047,23226,3511,-1,-1,1000128809,2002,Female,African American,CRO,7217,80004740319,1,First Entry,2010-05-21,2010-12-22,2010,8,N,N,216,106773,CYF,CYF,Non-Posted,Paid,7307,2010-05-29,2010-12-22,2010,8,N,208,Y,2,2,2,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Foster Care,Kinship Care,12578,84,Return Home (Ends the Home Removal),Good,NaN
13,13,43724,800048,72650,11440,-1,-1,1000520267,2008,Female,African American,CRO,2770,80004840326,2,Reentry,2010-05-28,2010-12-22,2010,2,N,N,209,31227,CYF,CYF,Non-Posted,Paid,7303,2010-05-29,2010-12-11,2010,2,N,197,Y,1,2,2,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Foster Care,Kinship Care,12578,84,Return Home (Ends the Home Removal),Good,NaN
14,14,43724,800048,72650,58186,-1,-1,1000520267,2008,Female,African American,CRO,28453,80004842450,3,Reentry,2016-03-21,2016-04-07,2016,8,N,N,17,NaN,CYF,CYF,Non-Posted,Paid,56599,2016-03-21,2016-04-07,2016,8,N,18,Y,1,3,3,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Foster Care,Kinship Care,23660,84,Return Home (Ends the Home Removal),Good,NaN
15,15,61660,800095,13784,49468,-1,-1,1000096668,1997,Female,African American,JPO,24067,80009542012,1,First Entry,2015-01-08,2015-01-14,2015,17,N,N,7,NaN,JPO,JPO,Non-Paid,Non-Paid,48780,2015-01-08,2015-01-14,2015,17,N,7,Y,1,1,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
16,16,61660,800095,13784,50995,-1,-1,1000096668,1997,Female,African American,JPO,24963,80009542123,2,Reentry,2015-04-29,2015-05-01,2015,17,N,N,3,NaN,JPO,JPO,Non-Paid,Non-Paid,50120,2015-04-29,2015-05-01,2015,17,N,3,Y,1,2,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
17,17,61660,800096,13782,18913,-1,-1,1000096667,1999,Female,African American,NaN,10013,80009640707,1,First Entry,2011-06-13,2011-06-14,2011,12,N,N,2,69809,JPO,JPO,Non-Paid,Non-Paid,18960,2011-06-13,2011-06-14,2011,12,N,2,Y,1,1,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,976,976,Return Home (Ends the Home Removal),Good,NaN
18,18,61660,800096,13782,45052,-1,-1,1000096667,1999,Female,African American,JPO,19175,80009641570,2,Reentry,2013-10-23,2014-12-30,2013,14,N,N,434,69809,JPO,JPO,JPO,Paid,44386,2014-06-29,2014-12-30,2014,15,N,185,Y,6,7,NaN,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Congregate Care,Congregate Care,15494,347,Return Home (Ends the Home Removal),Good,NaN
19,19,61660,800096,13782,58399,-1,-1,1000096667,1999,Female,African American,JPO,24500,80009642068,3,Reentry,2015-03-05,2016-08-11,2015,16,N,N,526,NaN,CYF,Both,Non-Paid,Non-Paid,56751,2016-03-30,2016-08-11,2016,17,N,135,Y,5,12,1,Placement Exit,Return Home (Ends the Home Removal),Return Home,Return Home,Alternate Location,Other/Alternative,14941,14908,Return Home (Ends the Home Removal),Good,NaN

In [215]:
self.data.HOME_RMVL_KEY.value_counts()

884      26
9030     25
2148     24
6396     23
4551     22
8613     20
16398    20
8197     20
5860     20
6093     19
723      19
4435     19
11212    18
6056     18
11934    18
14045    18
9548     18
4328     18
3534     17
19594    17
5348     17
2817     17
2915     17
11612    17
9852     17
17639    16
16441    16
10899    16
8090     16
12265    16
         ..
14900     1
10806     1
8759      1
23096     1
16955     1
29245     1
27198     1
25151     1
531       1
2578      1
4625      1
6672      1
12757     1
8663      1
20953     1
18906     1
29149     1
27102     1
25055     1
4593      1
2546      1
499       1
14836     1
23032     1
20985     1
18938     1
16891     1
27134     1
25087     1
2049      1
Name: HOME_RMVL_KEY, dtype: int64

In [217]:
self.data.ix[self.data[self.house_str] == 884, :]

,Unnamed: 0,CASE_REF_ID,CLIENT_ID,CL_KEY,PLCMNT_KEY,ABS_KEY,ALT_LOC_KEY,MCI_ID,BIRTH_YEAR,GENDER,RACE_GROUP,REG_OFFICE_RMVLDT,HOME_RMVL_KEY,CLIENT_RMVLDT,HOME_RMVL_SEQ_NBR,RMVL_TYPE,RMVL_DATE,RTRN_DATE,RMVL_YEAR,RMVL_AGE,RMVL_OPEN_PLMT,RMVL_OPEN,RMVL_LOS,RMVD_FRM_CL_KEY,PLCMNT_TYPE,RMVL_TYPE.1,Placement.Referral.Type,TYPE_PLACEMENT,PLCMNT_SEQ_NBR,ANALYSIS_ENTRY_DT,ANALYSIS_EXIT_DT,PLMT_YEAR,PLMT_AGE,PLMT_OPEN,PLMT_LOS,RMVL_LATEST_PLMT,RMVL_PLMT_NO,CLIENT_PLMT_NO,CLIENT_CYF_PLMT_NO,CW.Exit.Reason.Type,CW.Exit.Reason,Placement.Exit.Reason,End.Care.Reason,SRVC_GROUP_2,ANALYSIS_CARETYPE,FACILITY_ID,AGENCY_ID,exit_reason,desirability,notes
19575,19575,44339,814400,42207,56212,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,54846,2015-12-14,2016-03-24,2015,12,N,102,N,21,21,21,Placement End,Placement/Custody by Juvenile Probation,No Data,NaN,Congregate Care,Congregate Care,17805,46,Placement/Custody by Juvenile Probation,Bad,NaN
26235,26235,44339,814400,42207,58685,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,JPO,Both,Non-Paid,Non-Paid,57047,2016-03-24,2016-04-13,2016,13,N,21,N,22,22,NaN,Placement End,Court Ordered (For JPO use only),No Data,NaN,Congregate Care,Congregate Care,976,976,Court Ordered (For JPO use only),Bad,NaN
28273,28273,44339,814400,42207,24921,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Shelter,Paid,24998,2012-03-29,2012-03-30,2012,9,N,2,N,10,10,10,Placement End,**Placed in Group / Residential**,No Data,NaN,Foster Care,Foster Care,7227,399,**Placed in Group / Residential**,Bad,** means that it is a historical value not cur...
30937,30937,44339,814400,42207,24957,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Shelter,Paid,25004,2012-03-30,2012-06-15,2012,9,N,78,N,11,11,11,Placement End,**Youth Requires Different Level of Care**,No Data,NaN,Congregate Care,Congregate Care,2831,46,**Youth Requires Different Level of Care**,Bad,"I would say this is mostly bad, because it gen..."
31140,31140,44339,814400,42207,6869,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,5048,2010-01-22,2010-02-20,2010,6,N,30,N,2,2,2,Placement End,Placement Cannot Meet the Child's Behavioral T...,No Data,NaN,Foster Care,Foster Care,2273,116,Placement Cannot Meet the Child's Behavioral T...,Bad,NaN
31141,31141,44339,814400,42207,6867,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Online Service Request,Paid,7936,2010-06-09,2011-03-30,2010,7,N,295,N,5,5,5,Placement End,Placement Cannot Meet the Child's Behavioral T...,No Data,NaN,Foster Care,Foster Care,11909,165,Placement Cannot Meet the Child's Behavioral T...,Bad,NaN
31142,31142,44339,814400,42207,43990,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,43337,2014-06-13,2014-12-30,2014,11,N,201,N,17,17,17,Placement End,Placement Cannot Meet the Child's Behavioral T...,No Data,NaN,Foster Care,Foster Care,15957,686,Placement Cannot Meet the Child's Behavioral T...,Bad,NaN
32035,32035,44339,814400,42207,49094,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,48430,2015-02-03,2015-08-14,2015,11,N,193,N,19,19,19,Placement End,Placement with Kinship Caregiver,No Data,NaN,Congregate Care,Congregate Care,17805,46,Placement with Kinship Caregiver,Good,Includes fictive kin
32836,32836,44339,814400,42207,60622,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,58588,2016-06-29,NaN,2016,13,Y,58,Y,26,26,25,No Data,No Data,No Data,NaN,Congregate Care,Congregate Care,15338,354,No Data,Placement still open,NaN
35358,35358,44339,814400,42207,6872,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,4950,2010-01-13,2010-01-22,2010,6,N,10,N,1,1,1,Placement End,**Placed in Facility Foster Home**,No Data,NaN,Foster Care,Kinship Care,12068,90,**Placed in Facility Foster Home**,Good,"Most likely going from shelter FH to perm FH, ..."
35359,35359,44339,814400,42207,6866,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Paid,Non-Paid,9061,2010-02-21,2010-04-14,2010,6,N,53,N,3,3,3,Placement End,**Placed in Facility Foster Home**,No Data,NaN,Alternate Location,Other/Alternative,10828,90,**Placed in Facility Foster Home**,Good,"Most likely going from shelter FH to perm FH, ..."
35360,35360,44339,814400,42207,19131,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,19217,2011-07-22,2011-08-19,2011,8,N,29,N,7,7,7,Placement End,**Placed in Facility Foster Home**,No Data,NaN,Foster Care,Kinship Care,16646,90,**Placed in Facility Foster Home**,Good,"Most likely going from shelter FH to perm FH, ..."
35361,35361,44339,814400,42207,26658,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,26671,2012-06-15,2013-03-11,2012,9,N,270,N,12,12,12,Placement End,**Placed in Facility Foster Home**,No Data,NaN,Congregate Care,RTF,1652,81,**Placed in Facility Foster Home**,Good,"Most likely going from shelter FH to perm FH, ..."
35362,35362,44339,814400,42207,33740,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,33136,2013-03-11,2013-05-17,2013,10,N,68,N,13,13,13,Placement End,**Placed in Facility Foster Home**,No Data,NaN,Foster Care,Foster Care,9625,663,**Placed in Facility Foster Home**,Good,"Most likely going from shelter FH to perm FH, ..."
36678,36678,44339,814400,42207,20178,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,20259,2011-08-19,2012-03-29,2011,8,N,224,N,9,9,9,Placement End,Agency Requested Change of Placement,No Data,NaN,Foster Care,Kinship Care,16819,22,Agency Requested Change of Placement,Bad,Usually 30 day notice from foster parents they...
38811,38811,44339,814400,42207,6868,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Shelter,Paid,6279,2010-04-15,2010-06-09,2010,7,N,56,N,4,4,4,Placement End,Change in Facility Foster Home Status,No Data,NaN,Foster Care,Foster Care,165,NaN,Change in Facility Foster Home Status,Good,shelter to regular FH
38812,38812,44339,814400,42207,19698,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Online Service Request,Paid,19769,2011-08-19,2011-08-19,2011,8,N,1,N,8,8,8,Placement End,Change in Facility Foster Home Status,No Data,NaN,Foster Care,Foster Care,7572,22,Change in Facility Foster Home Status,Good,shelter to regular FH
44553,44553,44339,814400,42207,36745,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,36147,2013-05-17,2013-08-13,2013,10,N,89,N,14,14,14,Placement End,Child is Hospitalized,No Data,NaN,Foster Care,Foster Care,19408,663,Child is Hospitalized,Bad,NaN
45004,45004,44339,814400,42207,16757,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,16941,2011-03-30,2011-07-22,2011,8,N,115,N,6,6,6,Placement End,**Placed in CYF Foster Home**,No Data,NaN,Foster Care,Foster Care,12464,165,**Placed in CYF Foster Home**,Contextual,Shouldn't be used often in our data
45222,45222,44339,814400,42207,38702,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,38084,2013-10-16,2014-06-13,2013,10,N,241,N,16,16,16,Placement End,Placement in Pre-Adoptive Home,No Data,NaN,Congregate Care,Congregate Care,17805,46,Placement in Pre-Adoptive Home,Good,NaN
45576,45576,44339,814400,42207,53454,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,52408,2015-08-14,2015-12-14,2015,12,N,123,N,20,20,20,Placement End,Foster Parent(s) Requested Change of Placement,No Data,NaN,Foster Care,Kinship Care,22820,84,Foster Parent(s) Requested Change of Placement,Bad,NaN
46023,46023,44339,814400,42207,48092,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Shelter,Paid,47394,2014-12-30,2015-02-03,2014,11,N,36,N,18,18,18,Placement End,Facility Change within Same Provider - Change ...,No Data,NaN,Congregate Care,Congregate Care,2831,46,Facility Change within Same Provider - Change ...,Not a Move,Fiscal change not an actual move
46024,46024,44339,814400,42207,59062,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,57349,2016-04-13,2016-05-09,2016,13,N,27,N,23,23,22,Placement End,Facility Change within Same Provider - Change ...,No Data,NaN,Congregate Care,Congregate Care,13035,354,Facility Change within Same Provider - Change ...,Not a Move,Fiscal change not an actual move
46604,46604,44339,814400,42207,37522,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Shelter,Paid,36904,2013-08-23,2013-10-16,2013,10,N,55,N,15,15,15,Placement End,Facility Change within Same Provider - Same Le...,No Data,NaN,Congregate Care,Congregate Care,2831,46,Facility Change within Same Provider - Same Le...,Not a Move,Fiscal change not an actual move
46605,46605,44339,814400,42207,59416,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,57680,2016-05-09,2016-06-03,2016,13,N,26,N,24,24,23,Placement End,Facility Change within Same Provider - Same Le...,No Data,NaN,Congregate Care,Congregate Care,15314,354,Facility Change within Same Provider - Same Le...,Not a Move,Fiscal change not an actual move
46606,46606,44339,814400,42207,60627,-1,-1,1000334135,2003,Male,African American,MVRO,884,81440040191,1,First Entry,2010-01-13,NaN,2010,6,Y,Y,2417,17924,CYF,Both,Non-Posted,Paid,58587,2016-06-03,2016-06-29,2016,13,N,27,N,25,25,24,Placement End,Facility Change within Same Provider - Same Le...,No Data,NaN,Congregate Care,Congregate Care,15312,354,Facility Change within Same Provider - Same Le...,Not a Move,Fiscal change not an actual move

In [ ]:
self.data.